"""HTTP route handlers.

Endpoints
---------
* ``GET  /``                       - service info.
* ``GET  /health``                 - liveness/readiness probe.
* ``GET  /v1/emotions``            - list supported inline emotion tags.
* ``POST /v1/audio/speech``        - synthesise speech (returns audio bytes).
* ``POST /v1/audio/speech/batch``  - synthesise + stitch multiple segments.

The engine is stored on ``app.state.engine`` by the app factory; handlers reach
it via the FastAPI ``Request`` object.

Full interactive documentation (every field, type, default, constraint) is
auto-generated by FastAPI from this module's docstrings and the schemas in
``schemas.py`` - see ``/docs`` (Swagger UI) or ``/openapi.json``. This module's
docstrings are written to read well there, not just here.
"""

from __future__ import annotations

import time
from typing import List

from fastapi import APIRouter, HTTPException, Request, Response

from .. import __version__, audio, budget, constants, emotions
from ..config import Settings
from ..engine import GenerationParams, Maya1Engine
from ..logging_setup import get_logger
from .schemas import (
    EmotionsResponse,
    HealthResponse,
    InfoResponse,
    SpeechBatchRequest,
    SpeechRequest,
    SpeechSegment,
)

logger = get_logger("maya1.api")

router = APIRouter()


def _engine(request: Request) -> Maya1Engine:
    engine = getattr(request.app.state, "engine", None)
    if engine is None:
        raise HTTPException(status_code=503, detail="Engine not initialised.")
    return engine


def _resolve_params(
    s: Settings,
    text: str,
    *,
    max_new_tokens: int | None,
    min_new_tokens: int | None,
    temperature: float | None,
    top_p: float | None,
    repetition_penalty: float | None,
) -> GenerationParams:
    """Build a :class:`GenerationParams`, auto-estimating `max_new_tokens` from
    `text` length when the caller didn't supply one explicitly."""
    resolved_max = max_new_tokens or budget.estimate_max_new_tokens(
        text,
        chars_per_second=s.auto_tokens_chars_per_second,
        headroom=s.auto_tokens_headroom,
        floor_tokens=s.auto_tokens_floor,
        ceiling_tokens=s.max_new_tokens,
    )
    return GenerationParams(
        max_new_tokens=resolved_max,
        min_new_tokens=min_new_tokens or s.min_new_tokens,
        temperature=s.temperature if temperature is None else temperature,
        top_p=s.top_p if top_p is None else top_p,
        repetition_penalty=(
            s.repetition_penalty if repetition_penalty is None else repetition_penalty
        ),
    )


@router.get("/", response_model=InfoResponse, tags=["meta"])
def info(request: Request) -> InfoResponse:
    s = request.app.state.settings
    return InfoResponse(
        name="maya1-server",
        version=__version__,
        backend="gguf" if s.use_gguf else "transformers",
        model_repo=s.model_repo,
        gguf_repo=s.gguf_repo if s.use_gguf else None,
        gguf_filename=s.gguf_filename if s.use_gguf else None,
        snac_repo=s.snac_repo,
        sample_rate=constants.SAMPLE_RATE,
        description_format='<description="...voice design..."> text with <emotion> tags',
        docs_url="/docs",
    )


@router.get("/health", response_model=HealthResponse, tags=["meta"])
def health(request: Request) -> HealthResponse:
    engine = _engine(request)
    s = request.app.state.settings
    return HealthResponse(
        status="ok" if engine.is_loaded else "loading",
        model_loaded=engine.is_loaded,
        model_repo=s.model_repo,
        backend="gguf" if s.use_gguf else "transformers",
        device=engine.device,
        version=__version__,
    )


@router.get("/v1/emotions", response_model=EmotionsResponse, tags=["meta"])
def list_emotions() -> EmotionsResponse:
    return EmotionsResponse(
        emotions=list(emotions.EMOTION_TAGS),
        tags=emotions.as_tags(),
        count=len(emotions.EMOTION_TAGS),
    )


@router.post("/v1/audio/speech", tags=["speech"])
def create_speech(request: Request, body: SpeechRequest) -> Response:
    engine = _engine(request)
    s = request.app.state.settings

    if not engine.is_loaded:
        raise HTTPException(status_code=503, detail="Model still loading; retry shortly.")

    text = body.input.strip()
    if not text:
        raise HTTPException(status_code=422, detail="`input` must not be empty.")
    if len(text) > s.max_input_chars:
        raise HTTPException(
            status_code=422,
            detail=f"`input` exceeds max_input_chars ({s.max_input_chars}).",
        )

    description = body.resolved_description(s.default_description)
    params = _resolve_params(
        s,
        text,
        max_new_tokens=body.max_new_tokens,
        min_new_tokens=body.min_new_tokens,
        temperature=body.temperature,
        top_p=body.top_p,
        repetition_penalty=body.repetition_penalty,
    )

    try:
        result = engine.generate(description=description, text=text, params=params)
    except RuntimeError as exc:
        logger.error("Synthesis failed: %s", exc)
        raise HTTPException(status_code=422, detail=str(exc)) from exc
    except Exception as exc:  # pragma: no cover - unexpected backend failure
        logger.exception("Unexpected synthesis error")
        raise HTTPException(status_code=500, detail="Internal synthesis error.") from exc

    if body.response_format == "pcm":
        payload = audio.float_to_pcm16(result.audio)
    else:
        payload = audio.encode_wav(result.audio)

    headers = {
        "X-Audio-Duration-Seconds": f"{result.duration_sec:.3f}",
        "X-Generated-Tokens": str(result.generated_tokens),
        "X-Elapsed-Seconds": f"{result.elapsed_sec:.3f}",
    }
    return Response(
        content=payload,
        media_type=audio.CONTENT_TYPES[body.response_format],
        headers=headers,
    )


@router.post("/v1/audio/speech/batch", tags=["speech"])
def create_speech_batch(request: Request, body: SpeechBatchRequest) -> Response:
    """Synthesise multiple segments and return one stitched-together clip.

    Each entry in `segments` is generated as its own independent inference
    call (own auto-estimated token budget unless it/the batch overrides one),
    then concatenated in order with `gap_ms` of silence between clips. This is
    the recommended way to produce a single file covering several distinct
    lines or emotions - a single generation call asked to cover that much
    ground in one `input` string degrades badly (drift, garbled audio) well
    before it would even hit a token limit.

    Response headers mirror the single-segment endpoint (`X-Audio-Duration-Seconds`,
    `X-Elapsed-Seconds`) for the combined clip, plus `X-Segment-Durations-Seconds`
    and `X-Segment-Tokens`: comma-separated per-segment values, in input order.
    """
    engine = _engine(request)
    s = request.app.state.settings

    if not engine.is_loaded:
        raise HTTPException(status_code=503, detail="Model still loading; retry shortly.")

    default_description = body.resolved_description(s.default_description)

    segments: List[SpeechSegment] = body.segments
    texts: List[str] = []
    for i, segment in enumerate(segments):
        text = segment.input.strip()
        if not text:
            raise HTTPException(
                status_code=422, detail=f"segments[{i}].input must not be empty."
            )
        if len(text) > s.max_input_chars:
            raise HTTPException(
                status_code=422,
                detail=f"segments[{i}].input exceeds max_input_chars ({s.max_input_chars}).",
            )
        texts.append(text)

    t0 = time.perf_counter()
    waveforms = []
    seg_durations: List[str] = []
    seg_tokens: List[str] = []

    for i, (segment, text) in enumerate(zip(segments, texts)):
        description = segment.description or default_description
        params = _resolve_params(
            s,
            text,
            max_new_tokens=segment.max_new_tokens or body.max_new_tokens,
            min_new_tokens=segment.min_new_tokens or body.min_new_tokens,
            temperature=segment.temperature if segment.temperature is not None else body.temperature,
            top_p=segment.top_p if segment.top_p is not None else body.top_p,
            repetition_penalty=(
                segment.repetition_penalty
                if segment.repetition_penalty is not None
                else body.repetition_penalty
            ),
        )
        logger.info(
            "batch: segment %d/%d starting (%d chars, budget up to %d tokens)",
            i + 1, len(segments), len(text), params.max_new_tokens,
        )
        try:
            result = engine.generate(description=description, text=text, params=params)
        except RuntimeError as exc:
            logger.error("Batch synthesis failed on segment %d: %s", i, exc)
            raise HTTPException(
                status_code=422, detail=f"segments[{i}]: {exc}"
            ) from exc
        except Exception as exc:  # pragma: no cover - unexpected backend failure
            logger.exception("Unexpected synthesis error on segment %d", i)
            raise HTTPException(
                status_code=500, detail=f"Internal synthesis error on segments[{i}]."
            ) from exc

        waveforms.append(result.audio)
        seg_durations.append(f"{result.duration_sec:.3f}")
        seg_tokens.append(str(result.generated_tokens))
        logger.info(
            "batch: segment %d/%d done (%.2fs audio, %d tokens, %.2fs elapsed)",
            i + 1, len(segments), result.duration_sec, result.generated_tokens,
            result.elapsed_sec,
        )

    combined = audio.concatenate_waveforms(
        waveforms, gap_ms=body.gap_ms, sample_rate=constants.SAMPLE_RATE
    )
    elapsed = time.perf_counter() - t0
    duration_sec = len(combined) / constants.SAMPLE_RATE

    if body.response_format == "pcm":
        payload = audio.float_to_pcm16(combined)
    else:
        payload = audio.encode_wav(combined)

    headers = {
        "X-Audio-Duration-Seconds": f"{duration_sec:.3f}",
        "X-Elapsed-Seconds": f"{elapsed:.3f}",
        "X-Segment-Count": str(len(segments)),
        "X-Segment-Durations-Seconds": ",".join(seg_durations),
        "X-Segment-Tokens": ",".join(seg_tokens),
    }
    return Response(
        content=payload,
        media_type=audio.CONTENT_TYPES[body.response_format],
        headers=headers,
    )
